name: PHP CI

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  composer:
    name: Composer config validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Validate composer configuration
        run: make validate

  php:
    name: PHP ${{ matrix.php-version }} (${{ matrix.dependencies }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '7.2', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4' ]
        dependencies: [ default ]
        include:
          - php-version: '7.2'
            dependencies: lowest
    steps:
      - uses: actions/checkout@v7
      - name: Install Composer dependencies (default)
        if: matrix.dependencies == 'default'
        run: make install PHP_VERSION=${{ matrix.php-version }}
      - name: Install Composer dependencies (lowest)
        if: matrix.dependencies == 'lowest'
        run: make install PHP_VERSION=${{ matrix.php-version }} DEPENDENCIES_LOWEST=1
      - name: Audit Composer dependencies
        if: matrix.php-version == '7.2' && matrix.dependencies == 'default'
        run: make audit
      - name: Check PHP syntax
        run: make lint PHP_VERSION=${{ matrix.php-version }}
      - name: Run PHPCS
        run: make sniff PHP_VERSION=${{ matrix.php-version }}
      - name: Run PHPUnit
        run: make test PHP_VERSION=${{ matrix.php-version }}
